service: sti-mashup-api

package:
  patterns:
    - 'artifact/**/*'
    - '!.vscode/**'
    - '!.git/**'
    - '!.serverless/**'
    - '!.build/**'
    - '!dist/**'
    - '!nodemon*'
    - '!test.js'

useDotenv: true

plugins:
  - serverless-plugin-log-retention
  - serverless-offline

custom:
  logRetentionInDays: 7

  tscpaths:
    buildPath: .build

  optimize:
    exclude: ['@ntegral/nestjs-sentry']

provider:
  name: aws
  region: ap-northeast-2
  profile: sideteam-serverless-local
  runtime: nodejs14.x
  memorySize: 256
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        # IAMCredentials - https://gist.github.com/dhavaln/27a688f99169166398795c6b9adaa427
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:BatchGetItem
            - dynamodb:BatchWriteItem
          Resource: 'arn:aws:dynamodb:${self:provider.region}:*:table/*'
        - Effect: Allow
          Action:
            - sqs:GetQueueAttributes
            - sqs:SendMessage
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
          Resource: 'arn:aws:sqs:${self:provider.region}:*:*'
        - Effect: Allow
          Action:
            - s3:DeleteObject
            - s3:GetObject
            - s3:PutObject
          Resource: 'arn:aws:s3:::sti-data-${sls:stage}/*'
